import { v } from "convex/values";
import { getAuthUserId } from "@convex-dev/auth/server";
import { mutation, query } from "./_generated/server";

/**
 * Access-code gating. A registered subscriber may only read recipes
 * after redeeming a valid 8-character access code generated by the admin.
 */

/** Whether the current user has redeemed a valid access code. */
export const status = query({
  args: {},
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (userId === null) return { hasAccess: false, signedIn: false };
    const user = await ctx.db.get(userId);
    const email = user?.email;
    if (!email) return { hasAccess: false, signedIn: true };
    const redeemed = await ctx.db
      .query("accessCodes")
      .withIndex("by_used_email", (q) => q.eq("usedByEmail", email))
      .first();
    return { hasAccess: redeemed !== null, signedIn: true };
  },
});

/** Check a code without redeeming it. */
export const validate = mutation({
  args: { code: v.string() },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (userId === null) throw new Error("سجّل الدخول أولاً");
    const user = await ctx.db.get(userId);
    const email = user?.email;
    if (!email) throw new Error("تعذّر التحقق من حسابك");

    // Already redeemed by this account?
    const already = await ctx.db
      .query("accessCodes")
      .withIndex("by_used_email", (q) => q.eq("usedByEmail", email))
      .first();
    if (already) return { ok: true as const, message: "لديك وصول بالفعل" };

    const normalized = args.code.trim().toUpperCase();
    const record = await ctx.db
      .query("accessCodes")
      .withIndex("by_code", (q) => q.eq("code", normalized))
      .first();

    if (!record) return { ok: false as const, message: "الكود غير صحيح" };
    if (record.usedByEmail && record.usedByEmail !== email) {
      return { ok: false as const, message: "هذا الكود مستخدم من قبل حساب آخر" };
    }
    return { ok: true as const, message: "الكود صحيح — يمكنك المتابعة" };
  },
});

/** Redeem a valid code for the current account (one code per account). */
export const redeem = mutation({
  args: { code: v.string() },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (userId === null) throw new Error("سجّل الدخول أولاً");
    const user = await ctx.db.get(userId);
    const email = user?.email;
    if (!email) throw new Error("تعذّر التحقق من حسابك");

    // Already has access?
    const already = await ctx.db
      .query("accessCodes")
      .withIndex("by_used_email", (q) => q.eq("usedByEmail", email))
      .first();
    if (already) return { ok: true as const, message: "لديك وصول بالفعل" };

    const normalized = args.code.trim().toUpperCase();
    const record = await ctx.db
      .query("accessCodes")
      .withIndex("by_code", (q) => q.eq("code", normalized))
      .first();

    if (!record) return { ok: false as const, message: "الكود غير صحيح" };
    if (record.usedByEmail && record.usedByEmail !== email) {
      return { ok: false as const, message: "هذا الكود مستخدم من قبل حساب آخر" };
    }

    await ctx.db.patch(record._id, {
      usedAt: Date.now(),
      usedByEmail: email,
    });
    return { ok: true as const, message: "تم تنشيط اشتراكك بنجاح" };
  },
});
